### ISSUE TITLE
Support 1.13.2 

### ISSUE THREAD

**Issue by muntder123** [Delta-Development/DeltaCore#3]
Can you please add support for the CustomHead? <?
![image](https://user-images.githubusercontent.com/32172063/139510529-8df3c393-0a6a-4b0b-9dfa-586962a53a39.png)
![image](https://user-images.githubusercontent.com/32172063/139510537-e34c1bf2-8553-40ac-9432-815ddd8c81f0.png)

**Comment by NegativeKB** [comment]
Fixed. But there does not seem to be an issue with Custom Skulls. If you could elaborate or send any error/stacktrace screenshots that will clarify what I'm actually looking for.

Also this is untested, so if you could test the update and let me know if this works, I would also appreciate it.

**Comment by muntder123** [comment]
iam trying to use 1.13.2 for my plugin .. but its not working ..  i added the new version and this error apear:
![image](https://user-images.githubusercontent.com/32172063/139528086-5d79d606-17de-4c32-aaa2-f9a5aef4d472.png)

**Comment by muntder123** [comment]
the problem is still there .. not work on 1.13.2 ..

**Comment by hypewsthedev** [comment]
Recently changed the api version in our 1_13 plugin.yml. Can you try to build this yourself and try again?

**Comment by NegativeKB** [comment]
Tested and confirmed fix. Closing
